### ISSUE TITLE
设置按钮字体颜色怎么搞？

### ISSUE THREAD

**Issue by tianqiujie** [drakeet/MaterialDialog#31]
设置按钮字体颜色怎么搞？ 能不能加上呢 谢谢

**Comment by LanceCong** [comment]
同问。看看源码先

**Comment by drakeet** [comment]
不支持。。。官方已经有兼容库了，所以这个库不会再很多拓展，保持轻量。如果需要很多特性，请使用官方的 Material Dialog 兼容库

**Comment by drakeet** [comment]
现在可以获取到 button，然后改变之。
