### ISSUE TITLE
对话框用setcontentView进去 这个样子

### ISSUE THREAD

**Issue by tianqiujie** [drakeet/MaterialDialog#33]
![fz vr9govwk 68 o4n 5d](https://cloud.githubusercontent.com/assets/2835129/7203319/5df02268-e54c-11e4-8032-aeeefecb1410.png)
![Uploading FZ(@VR9GOVWK{{68)O4N`5D.png . . .]()

**Comment by drakeet** [comment]
怎么了？

**Comment by xlievo** [comment]
VIEW下面有间隙...VIEW位置不对，请修复BUG~不谢
