### ISSUE TITLE
dialog样式错误

### ISSUE THREAD

**Issue by yarnping** [drakeet/MaterialDialog#48]
![image](https://cloud.githubusercontent.com/assets/8018268/14170257/507957dc-f75f-11e5-988c-8ba858385349.png)

有一白色块背景是什么

**Comment by drakeet** [comment]
系统版本是？

yangping.wang <notifications@github.com>于2016年3月31日周四 16:40写道：

**Comment by yarnping** [comment]
ANDROID 4.4.4

**Comment by yarnping** [comment]
5.1.1也是一样 @drakeet

**Comment by drakeet** [comment]
我这边使用4.4测试无法重现，你能否帮忙测试和修复下，非常感谢！

yangping.wang <notifications@github.com>于2016年3月31日周四 16:50写道：

**Comment by yarnping** [comment]
@drakeet 你看看是不是window的background
http://stackoverflow.com/questions/10795078/dialog-with-transparent-background-in-android

**Comment by Jacko07** [comment]
话说我也是这个bug  我4.2测试的

**Comment by Jacko07** [comment]
请问有解决的办法吗  这个dialog挺好看的 不能用可惜呀 !!!

**Comment by drakeet** [comment]
这个问题应该不难解决，判断一下系统版本，做兼容性解决即可，不过我最近特别忙，暂时解决不了，有空的帮忙解决一下，求 Pull Request

Jacko07 <notifications@github.com>于2016年4月15日周五 下午2:04写道：

**Comment by Jacko07** [comment]
...我是新手 t.t 兼容性什么的不太懂 爱莫能助  楼上链接的代码能去掉白框但是dialog里面的格式乱了,我本来想试一下使用楼上链接的方法修改 MaterialDialog里面的alertDialog.getView.xxx 但是java文件那里有个小锁,不能改动源码 0.0

**Comment by drakeet** [comment]
我的 4.0 4.2 都没法重现，增加了 `dialog.getWindow().setBackgroundDrawable(new ColorDrawable(android.graphics.Color.TRANSPARENT));`，你们有问题的再试试，好了的话，在这里告诉我一下。

**Comment by drakeet** [comment]
有可能 maven 中心库还没生效，试验的请等等它生效了，再引入测试。

![maven-central](https://img.shields.io/maven-central/v/me.drakeet.materialdialog/library.svg) 

```groovy
dependencies {
    compile 'me.drakeet.materialdialog:library:1.3.1'
}
```
