### ISSUE TITLE
RecyclerView

### ISSUE THREAD

**Issue by bruceyu1994** [drakeet/MaterialDialog#59]
RecyclerView支持吗，为什么我用RecyclerView没有显示 @drakeet

**Comment by drakeet** [comment]
`RecyclerView` 是支持的。但目前这个类库已经不推荐了，Android 官方提供了 `android.support.v7.app.AppCompatDialog` 或 `android.support.v7.app.AlertDialog` 来实现 Material Design Dialog

**Comment by bruceyu1994** [comment]
RecyclerView是支持的，多谢提示官方Dialog 库
